services:
  database:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/var/lib/postgresql
    environment:
      - "POSTGRES_DB=ultraqueue"
      - "POSTGRES_USER=dbknut"
      - "POSTGRES_PASSWORD=knutsdbpassword"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbknut -d ultraqueue"]
      interval: 5s
      timeout: 5s
      retries: 10



  application:
    image: ultraqueue:latest
    build:
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=database"
      - "DB_PORT=5432"
      - "DB_NAME=ultraqueue"
      - "DATABASEUSER=dbknut"
      - "DATABASEPASSWORD=knutsdbpassword"
    ports:
      - "8080:8080"
    volumes:
      - "~/.ultrastardx/songs:/ultrastardx/songs:ro"
    depends_on:
      database:
        condition: service_healthy
