spring.application.name=UltraQueue
server.port=8080
logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

# default for native installation:
ultraqueue.song-folder=${HOME}/.ultrastardx/songs
# default for flatpak:
#ultraqueue.song-folder=${HOME}/.var/app/eu.usdx.UltraStarDeluxe/.ultrastardx/songs
# default: one queued song per user
ultraqueue.max-songs-per-user=1
# default 60-minute repeat prohibition
ultraqueue.min-interval-minutes=60
ultraqueue.admin.username=admin
ultraqueue.admin.password=knutnix
# some mobile browsers are really slow!
ultraqueue.pagination.page-size=200