spring.application.name=UltraQueue
server.port=8080
ultraqueue=
    song-folder="/home/markus/.ultrastar/songs"
    # default: one queued song per user
    max-songs-per-user=1
    # default 60?minute repeat prohibition
    min-interval-minutes=60
    admin=
        username=admin
        password=knutnix
    pagination=
        # some mobile browsers are really slow!
        page-size=200
logging.level.root=INFO
logging.pattern.console=%d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n