package de.hhu.fscs.ultraqueue.web;

import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.stereotype.Component;
import org.springframework.web.util.WebUtils;

import java.awt.Color;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.Optional;

/**
 * Simple holder that extracts the “userId” cookie (generated by
 * UserIdInterceptor) and makes it available to the controllers.
 */
@Component
public class UserContext {

    public static final String COOKIE_NAME = "ULTRAQUEUE_USERID";
    private static final String COOKIE_SEPARATOR = "|"; // must not be a valid base64 character

    private UserContext() { /* utility class */ }

    /**
     * Returns the UUID stored in the UQUSER cookie, or throws
     * IllegalStateException if the interceptor has not run.
     */
    public static String getCurrentUserId(HttpServletRequest request) {
        // 1. Try to get it from request attributes (set by UserIdInterceptor during the current request)
        String attr = (String) request.getAttribute(COOKIE_NAME);
        if (attr != null) {
            return attr;
        }

        // 2. Fall back to reading the cookie (for subsequent requests)
        Cookie c = WebUtils.getCookie(request, COOKIE_NAME);
        if (c == null) {
            throw new IllegalStateException("UserId cookie missing – interceptor not configured");
        }
        return extractUserIdFromCookieValue(c.getValue());
    }

    /** Returns the stored username if present, otherwise empty. */
    public static Optional<String> getCurrentUsername(HttpServletRequest request) {
        Cookie c = WebUtils.getCookie(request, COOKIE_NAME);
        if (c == null) {
            return Optional.empty();
        }

        return Optional.ofNullable(extractUsernameFromCookieValue(c.getValue()))
                .filter(value -> !value.isBlank());
    }

    /** Persist the chosen username in the same cookie as the generated user id. */
    public static void setUsernameCookie(HttpServletResponse response, String userId, String username) {
        Cookie cookie = new Cookie(COOKIE_NAME, buildCookieValue(userId, username));
        cookie.setHttpOnly(true);
        cookie.setSecure(false);
        cookie.setPath("/");
        cookie.setMaxAge(60 * 60 * 24 * 2);
        response.addCookie(cookie);
    }

    /** Derive a stable, user-friendly color from the internal user id. */
    public static String getColorForUserId(String userId) {
        long hash = Integer.toUnsignedLong(userId.hashCode());
        float hue = (hash % 360) / 360.0f;
        Color color = Color.getHSBColor(hue, 0.55f, 0.82f);
        return "#%02x%02x%02x".formatted(color.getRed(), color.getGreen(), color.getBlue());
    }

    /** Build the raw cookie payload from user id + username. */
    public static String buildCookieValue(String userId, String username) {
        return extractUserIdFromCookieValue(userId) + COOKIE_SEPARATOR + encodeUsername(username);
    }

    /** Extract the generated user id from a raw cookie value. */
    public static String extractUserIdFromCookieValue(String rawValue) {
        if (rawValue == null || rawValue.isBlank()) {
            throw new IllegalStateException("UserId cookie missing – interceptor not configured");
        }
        int separator = rawValue.indexOf(COOKIE_SEPARATOR);
        return (separator >= 0) ? rawValue.substring(0, separator) : rawValue;
    }

    /** Extract the optional username from a raw cookie value. */
    public static String extractUsernameFromCookieValue(String rawValue) {
        if (rawValue == null || rawValue.isBlank()) {
            return null;
        }
        int separator = rawValue.indexOf(COOKIE_SEPARATOR);
        if (separator < 0 || separator == rawValue.length() - 1) {
            return null;
        }

        try {
            byte[] decoded = Base64.getUrlDecoder().decode(rawValue.substring(separator + 1));
            return new String(decoded, StandardCharsets.UTF_8);
        } catch (IllegalArgumentException ignored) {
            return null;
        }
    }

    private static String encodeUsername(String username) {
        if (username == null || username.isBlank()) {
            throw new IllegalArgumentException("Username must not be blank");
        }
        return Base64.getUrlEncoder().withoutPadding()
                .encodeToString(username.trim().getBytes(StandardCharsets.UTF_8));
    }
}
