package de.hhu.fscs.ultraqueue.web;

import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.stereotype.Component;
import org.springframework.web.util.WebUtils;

/**
 * Simple holder that extracts the “userId” cookie (generated by
 * UserIdInterceptor) and makes it available to the controllers.
 */
@Component
public class UserContext {

    public static final String COOKIE_NAME = "ULTRAQUEUE_USERID";

    private UserContext() { /* utility class */ }

    /**
     * Returns the UUID stored in the UQUSER cookie, or throws
     * IllegalStateException if the interceptor has not run.
     */
    public static String getCurrentUserId(HttpServletRequest request) {
        // 1. Try to get it from request attributes (set by UserIdInterceptor during the current request)
        String attr = (String) request.getAttribute(COOKIE_NAME);
        if (attr != null) {
            return attr;
        }

        // 2. Fall back to reading the cookie (for subsequent requests)
        Cookie c = WebUtils.getCookie(request, COOKIE_NAME);
        if (c == null) {
            throw new IllegalStateException("UserId cookie missing – interceptor not configured");
        }
        return c.getValue();           // already a UUID string
    }
}
